// <auto-generated />
using Luan.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020235759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Luan.Models.ConsumoAgua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AdicionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("ConsumoFaturado")
                        .HasColumnType("REAL");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<double>("M3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("TaxaEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.Property<double>("ValorAgua")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Cpf", "Mes", "Ano")
                        .IsUnique();

                    b.ToTable("Consumos");
                });
#pragma warning restore 612, 618
        }
    }
}
